format_version: 3
pipelines:
  deploy_to_cluster:
    group: sample
    label_template: ${COUNT}
    lock_behavior: none
    display_order: 3
    environment_variables:
      IMAGE_NAME: "nginx"
      IMAGE_TAG: "latest"
      DEPLOYMENT_NAME: "nginx-deployment"
    materials:
      upstream:
        pipeline: test_application
        stage: test_app_image
        name: upstream_pipeline
      SourceCodeRepo:
        git: https://github.com/ClownandBox/GoCD-deploy.git
        shallow_clone: false
        auto_update: true
        branch: main
        name: SourceCodeRepo
    stages:
    - deploy_to_cluster:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          deploy:
          timeout: 0
          elastic_profile_id: demo-app
          tasks:
          - exec:
              arguments:
              command: ./app-deploy.sh
              run_if: passed