format_version: 3
pipelines:
  deploy_to_cluster:
    group: sample
    label_template: ${COUNT}
    lock_behavior: none
    display_order: 3
    environment_variables:
      IMAGE_NAME: "nginx"
      IMAGE_TAG: "latest"
      DEPLOYMENT_NAME: "nginx-deployment"
      KUBE_TOKEN: "eyJhbGciOiJSUzI1NiIsImtpZCI6IjdjZE5adjM2WmthNGFVYzEyMC1JM0w5NjJSQVVrQjdhQ0ZoUmFxWURJbDgifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzI2ODAyOTY4LCJpYXQiOjE3MjY3OTkzNjgsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJnb2NkIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImdvY2QtYWRtaW4iLCJ1aWQiOiI5ZjBhZDZmZi1jNDlkLTRiMmUtOTNmYS0xMTgzNjQwZTIwMTgifX0sIm5iZiI6MTcyNjc5OTM2OCwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmdvY2Q6Z29jZC1hZG1pbiJ9.0fgmZ7_RtKKQwSruFJaNcY-3Y7SCbM9Vzf1-WzNe5krz960TRwz4cYyFBANWDBbxivKdkpcV__SGpd_EM9tsKOOMa9-8VNUVCdn4mp7UY138Z4-e-HoyGr8ubFywNjx3tJOAFE2Efnl0kojxCQuvaEenEku-PfnQZES59jwfEyoCQBPZTG652HAxHoC0iqnhItsG_mUvNirJ1LdG_CaTj27ExUZbX9JjtWoD-ZAUhHgiAbvLGBMA4v1zMHzmCzW6Bc7kSndwKDtaIYD3w61PlGMCZLWAs17TRtehnXtoSehdDG_mVXN98aCClNAqYLlOF3AOKmrJiLUOiXSVxHhrQA"
    materials:
      SourceCodeRepo:
        git: https://github.com/ClownandBox/GoCD-deploy.git
        shallow_clone: false
        auto_update: true
        branch: main
        name: SourceCodeRepo
    stages:
    - deploy_to_cluster:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          deploy:
            timeout: 0
            tasks:
            - exec:
                command: bash
                arguments:
                  - "-c"
                  - "chmod 777 ./app-deploy.sh"
                run_if: passed
            - exec:
                arguments:
                command: ./app-deploy.sh
                run_if: passed